modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="more_compatibility"
version="1.2.0"
displayName="More compatibility"
displayURL="https://center.mcmod.cn/732581/"
logoFile="logo.png"
credits="月影听啼"
authors="月影听啼"
description="Make various modules compatible by adding labels"

[[dependencies.more_compatibility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




